### ISSUE TITLE
Lee’s Tetrahedric Conformal Projection?

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-projection#107]
in https://www.youtube.com/watch?v=fu-uW7CQkVo @jasondavies says it's one of his favourite
![capture d ecran 2017-04-08 14 18 15](https://cloud.githubusercontent.com/assets/7001/24828851/d1e0096a-1c66-11e7-8b9a-dfe8f4b7e8b8.png)

**Comment by mbostock** [comment]
Reference image from (Carlos Furuti)[http://www.progonos.com/furuti/MapProj/Normal/ProjPoly/Foldout/Tetrahedron/tetrahedron.html]:

<img width="742" alt="screen shot 2017-04-08 at 7 18 07 am" src="https://cloud.githubusercontent.com/assets/230541/24829690/9262f44a-1c2b-11e7-9726-85b00f33251c.png">

**Comment by Fil** [comment]
As a first step for this issue is the Tetrahedral Gnomonic projection, by A. J. Potter (1925)

[<img width="311" alt="tetrahedral gnomonic 1" src="https://cloud.githubusercontent.com/assets/7001/26034355/85af74a6-38bb-11e7-8277-c3e42e624a05.png">](https://bl.ocks.org/Fil/2da4da62950052d3bbb27857620fdab6)

There's a problem in my implementation though: when land covers the extreme point (ie the vertices or the triangle), as is the case in the aspect given in this block, the land path is flipped, and oceans are painted. I don't really know how to fix that.

The Antarctic-centered aspect doesn't have this problem: 
[<img width="445" alt="capture d ecran 2017-05-14 a 15 43 08" src="https://cloud.githubusercontent.com/assets/7001/26034439/cd25ada4-38bc-11e7-920b-42a527b664aa.png">](http://bl.ocks.org/Fil/e5b449606ca1e3e120cda8d08a7f3351)

**Comment by jkunimune15** [comment]
Does anyone actually know the equations for this projection? I've found several images of it on the internet, but no reference whatsoever as to how they are derived.

**Comment by Fil** [comment]
I found two reference papers. One by [Lee](http://www.utpjournals.press/toc/cart/13/1) (1976), and a more recent one by [McIlroy](http://www.cs.dartmouth.edu/~doug/wallpaper.pdf) (2011). The latter is much easier to read and might be the base for the R [mapproj](https://cran.r-project.org/web/packages/mapproj/index.html] implementation.

I'm currently working on implementing it for d3, but it's hard 🤖. It seemed easier to start with the related [Cox projection](https://bl.ocks.org/Fil/1aafd8fa22b62243290674384c364dd0). #118

**Comment by Fil** [comment]
Got a [Tetrahedral implementation](https://bl.ocks.org/Fil/5ad65a8075e634ab7e4de8ace95fb3c5)!

<img width="528" alt="" src="https://cloud.githubusercontent.com/assets/7001/26526799/9a99a308-4385-11e7-9011-3edbc64040b0.png">

I need to clean it a bit, but it works!

**Comment by Fil** [comment]
Almost there: https://bl.ocks.org/Fil/c36ed66a4d50d77150712c80642a78d5
<img width="585" alt="capture d ecran 2017-07-25 a 07 26 34" src="https://user-images.githubusercontent.com/7001/28557219-6b7fd796-710b-11e7-8e6e-dac24c0da810.png">

**Comment by Fil** [comment]
All set! 🤡

The last remaining issue was with the Sphere outline, which had defaults near the three south poles and was randomly missing some parts. I fixed it by specifying the exact contour. But then, it was clipped out by clipPolygon(). I fixed that by giving a lower epsilon to the Sphere outline than to the clipPolygon function. (Maybe the final version should use `epsilon / 100` in polyhedral/clipPolygon and `epsilon` for the Sphere. This ratio works.)

**Comment by Fil** [comment]
I've updated this with all the recent work in polyhedral and d3-geo-polygon, and it's working well. Check it out
http://blockbuilder.org/Fil/ce41e0e836b0e049c65c29358afef1d0

**Comment by Fil** [comment]
Now fully implemented in [d3-geo-polygon(newprojections branch)](https://github.com/d3/d3-geo-polygon/tree/newprojections), but it needs a new release of d3-geo (https://github.com/d3/d3-geo/pull/128) before it's usable.

**Comment by waldyrious** [comment]
For future reference, d3/d3-geo#128 was superseded by d3/d3-geo#130, which in turn was superseded by d3/d3-geo#132.

@Fil was this issue closed by accident? I don't see the projection listed anywhere.

**Comment by Fil** [comment]
It's in the d3-geo-polygon module : https://github.com/d3/d3-geo-polygon/blob/master/README.md#geoTetrahedralLee
