### ISSUE TITLE
Hufnagel projection ?

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-projection#112]
A family of pseudocylindric equal-area map projections by Herbert Hufnagel (1989).

<img width="633" alt="capture d ecran 2017-04-30 a 15 39 47" src="https://cloud.githubusercontent.com/assets/7001/25564812/571e2390-2dbb-11e7-9313-2fcc5144afb5.png">

Paper and algorithm
http://www.cartography.oregonstate.edu/pdf/2015_Jenny_etal_Hufnagel.pdf

![](http://map-projections.net/img/figs/hufnagel-4-halfflat.jpg)
http://map-projections.net/hufnagel.php

https://www.mapthematics.com/interactive/hufnagel.html has a Javascript implementation (licence unknown)

**Comment by TJung1968** [comment]
> https://www.mapthematics.com/interactive/hufnagel.html has
> a Javascript implementation (licence unknown)

That page is using code from CanvasMap which is licensed under GPL 2 (and includes Hufnagel):
https://github.com/OSUCartography/CanvasMap

**Comment by Fil** [comment]
@TJung1968 @berniejenny @beuan you're welcome to review https://github.com/d3/d3-geo-projection/pull/147
