### ISSUE TITLE
Cox conformal triangle projection?

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-projection#118]
This is a conformal projection, in which the sphere is transformed into an equilateral triangle. It might be useful,  as these triangles can be tiled to make a wallpaper 🤖. It is also a step in solving #107 

<img width="471" alt="" src="https://cloud.githubusercontent.com/assets/7001/26526418/db19cad0-437a-11e7-97e4-22d7c95360c7.png">

[Implementation with d3.js and references](https://bl.ocks.org/Fil/1aafd8fa22b62243290674384c364dd0).

and [north polar aspect](https://bl.ocks.org/Fil/ce9d55cc070126b66fb86bc03b84b3f4): 

<img width="471" alt="" src="https://cloud.githubusercontent.com/assets/7001/26526514/35a42be6-437e-11e7-8596-02a61dc7a398.png">

**Comment by Fil** [comment]
The formula is OK now — but if we wanted to integrate it in d3-geo-projection, there are two implementation details on which I'm seeking some advice:

\1) rotation aspect

of course using `.rotation([…,…,180])` will switch from the "South" to the "North" polar aspect, but the figure is rotated too (North is towards the bottom). We don't have a handy "post-projection" rotation, wouldn't it be useful (independently of the raw projection)?.

\2) complex arithmetic

d3 has no complex functions, except in guyou.js with complexDivide(). But it wouldn't make sense to create coxComplex, then leeComplex… (nothing fancy: we just need add, mul and pow).

In the meantime the block uses [complex.js](https://github.com/infusion/Complex.js). Compared to that, I think we'd be better off with a simpler API where _a + ib_ is represented by `[a,b]`.

**Comment by mbostock** [comment]
In the case of the transverse Mercator projection, I created a separate projection class (sharing the same base code) that applies the pre-projection and post-projection rotations. I didn’t feel it was necessary to generalize further than that.

Also, it’s faster to do planar rotations in the graphics layer, either as an SVG or a Canvas transform. Arguably we should be doing that for the post-projection scale and translate as well, but scale and translate don’t require trigonometric operations, and it *is* convenient to encapsulate it in the projection…

Regarding complex math, I’d probably start by breaking out any shared code used by the projections into a complex.js in src, like we do in [elliptic.js](https://github.com/d3/d3-geo-projection/blob/master/src/elliptic.js) and [math.js](https://github.com/d3/d3-geo-projection/blob/master/src/math.js).

**Comment by Fil** [comment]
I've begun moving things to `src/complex.js` but I'm having second thoughts about implementing "our own". Not that it's super-hard, but  https://github.com/infusion/Complex.js is a nice piece of software; it's well-tested and considers the difficult cases. In a way, it feels wrong not to use it. Sure, it has a different coding style. (There was the issue of using a vector API `[real, imaginary]`, but it's just been implemented.)

**Comment by mbostock** [comment]
I don’t want to add a dependency to this library, but you could publish a separate module, d3-geo-cox (or d3-geo-complex if there is a family of projections that want complex math) or similar.

**Comment by Fil** [comment]
here's some code with a new `complex.js` lib that is used by `guyou.js` and `cox.js`
https://github.com/d3/d3-geo-projection/compare/master...Fil:complex?expand=1

It's a draft branch, for comments. For a (future) PR I would submit a cleaner branch with less intermediary commits. There's no hurry in any case, as I still need to work on the big piece, aka polygon cutting, so that the Cox projection doesn't "bleed" along its edges (the bleeding is hidden by the Sphere).

**Comment by Fil** [comment]
Fixed in [d3-geo-polygon](https://github.com/d3/d3-geo-polygon).
See https://beta.observablehq.com/@fil/cox-conformal-projection-in-a-triangle
