### ISSUE TITLE
Projection problem with a simple polygon

### ISSUE THREAD

**Issue by Phazzer** [d3/d3-geo-projection#119]
Hi,

There is a problem with the projection of a polygon; the last point is excluded.

A work-around is to append a duplicate of the last point.

Here is a minimal codepen reproducing the issue: https://codepen.io/anon/pen/ZyKGqm

Thanks!

**Comment by Fil** [comment]
This is not a d3 issue.

Per the GEOJSON spec http://geojson.org/geojson-spec.html
> A LinearRing is closed LineString with 4 or more positions. *The first and last positions are equivalent (they represent equivalent points).* Though a LinearRing is not explicitly represented as a GeoJSON geometry type, it is referred to in the Polygon geometry type definition.
