### ISSUE TITLE
geoquantize?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo-projection#122]
Already possible using `geoproject -p k 'd3.geoIdentity()'` but it would be more concise and consistent to have a trivial CLI for d3.geoQuantize. /cc @Fil

**Comment by Fil** [comment]
See difficulties mentioned in https://github.com/d3/d3-geo-projection/pull/140#issuecomment-414655583 and a possible alternative approach in https://beta.observablehq.com/@fil/geoformat
