### ISSUE TITLE
Use d3-geo-polygon for polyhedral projections

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-projection#129]
port https://github.com/d3/d3-geo-projection/pull/124 to the new architecture:
- d3-geo/clip
- d3-geo-polygon

**Comment by Fil** [comment]
I'm not sure how to properly integrate this.

For http://blockbuilder.org/Fil/61bf310184055add159620a977112069 I baked d3-geo-polygon into d3-geo-projection.js by adding the following to `src/polyhedral/index.js`:
`import {geoClipPolygon as clipPolygon} from "../../node_modules/d3-geo-polygon/index";`
It works but seems ugly (there is nothing similar in the full d3 tree).

Of course, when I do a normal `import {geoClipPolygon as clipPolygon} from "d3-geo-polygon";`, clipPolygon is merely referenced. Do we want to force people to add `<script src="https://unpkg.com/d3-geo-polygon">` to be able to use (extended) polyhedral projections?

@mbostock can you advise?

**Comment by Fil** [comment]
I realise my question was focused on the technical issue, but maybe a clean separation will make it easier to experiment more freely on clipPolygon, while leaving d3-geo-projection untouched.


*Option A == bake clipPolygon into d3-geo-projection*

Pros:
- one file with all extended projections

Cons:
- the file is getting big
- the current polyhedral projections change a bit (very little: they don't need SVG or canvas clipping anymore — but some instability)
- no way to go to option B w/o breaking changes.

*Option B == work extended polyhedral in d3-geo-polygon*

Pros:
- smaller file size
- more room for experimentation (no consequence on d3-geo-projection)
- Easy to switch to option A at any time in the future

Cons:
- people who want to experiment "all" projections need to include two script tags
- duplication of d3.geoPolyhedral

(So now, I tend to think that option B is better.)

**Comment by mbostock** [comment]
Strong vote against code duplication.

Either add d3-geo-polygon as a dependency of d3-geo-projection, or move the projections that want d3-geo-polygon into d3-geo-polygon.
