### ISSUE TITLE
Wrong naming with deployed via bower

### ISSUE THREAD

**Issue by dboydor** [d3/d3-geo-projection#14]
In the "bower_components/d3-geo-projection" folder, the file name is:

d3.geo.projection.js

In the bower.json file, it has the "name" and "main" as "d3-geo-projection" and "d3-geo-projection.js".

In my Angular project, I'm using wiredeps and it's automatically including the "d3-geo-projection.js" file which can't be found since the file is using periods instead of dashes.

So the solution is to rename the file to use dashes or fix the bower.json config to use periods.

**Comment by mbostock** [comment]
Fixed in #19.
