### ISSUE TITLE
Nicolosi Globular projection?

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-projection#155]
Torben would you consider licensing this projection's code under the [BSD license](https://github.com/d3/d3-geo-projection/blob/master/LICENSE)?

Ref:
https://beta.observablehq.com/@toja/nicolosi-globular-projection
https://beta.observablehq.com/@toja/nicolosi-globular-inverse
by @toja (together: https://beta.observablehq.com/d/8965ead50c0b1937)

See also 
https://beta.observablehq.com/@toja/waldseemullers-gore-map

![image](https://user-images.githubusercontent.com/7001/48969320-71371600-effd-11e8-96ef-0ecafae7c858.png)

**Comment by toja** [comment]
@Fil Yes, sure.

**Comment by Fil** [comment]
I've just added this projection as a pull-request (#159).

I adapted your code a little bit: 
- the scale used for the inverse was unusual (changed it from [-2,2] to [-pi,pi])
- using the Newton-Raphson implementation from `src/newton.js`

thank you!

**Comment by toja** [comment]
I'm very glad to see that it's on its way now, thanks for implementig it @Fil

**Comment by Fil** [comment]
The projection is available in v2.6.0
Thank you @toja!
