### ISSUE TITLE
Missing "resolve" dependency

### ISSUE THREAD

**Issue by joearasin** [d3/d3-geo-projection#161]
https://www.npmjs.com/package/resolve is required by https://github.com/d3/d3-geo-projection/blob/master/bin/resolve.js, but not included as a dependency. This causes scripts to fail with `Cannot find module 'resolve'`

**Comment by Fil** [comment]
Indeed, it should have been in 1f7c5070115ac266b907dca7840754a43576b922.

Should be fixed by #162
