### ISSUE TITLE
Can this library be used to reproject a fisheye image into equirectangular projection?

### ISSUE THREAD

**Issue by jumpjack** [d3/d3-geo-projection#171]
I took a photo of a grid using my 235° FOV fisheye camera.
Can I use this library to reproject the image into equirectangular projection, assuming that I already know the coordinates of each grid intersection in source and destination images?

**Comment by Fil** [comment]
d3-geo-projection is mostly useful to project GeoJSON (vector) data, not bitmap/raster data such as an image.

In my view your question might be better answered with custom JS or WebGL code, such as
https://bl.ocks.org/fil/497d327919606ba6024cb13b4bee38a4

(This example goes FROM an equirectangular projected image TO the stereographic projection, you would probably have to use the inverse).
