### ISSUE TITLE
Relax d3-array dependency to 1-2.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo-projection#177]
Currently the package.json says this module depends on d3-array@1, but it‘s also compatible with d3-array@2, so we should allow that.

**Comment by Fil** [comment]
Setting `"d3-array": "1 - 2"` in package.json seems to work (all tests are green).

Note that d3-geo and probably quite a few other modules could benefit from the same.

**Comment by Fil** [comment]
I think we'll have the same webpack problem here as in https://github.com/d3/d3-geo/issues/176 ; reverting for now.

**Comment by Fil** [comment]
fixed in https://github.com/d3/d3-geo-projection/blob/ee1dd3f9b9db46cd7a1ed415694440ba9c411dc6/package.json (in two commits, ha!) for v3.0.0
