### ISSUE TITLE
There are es2015 in the final package file

### ISSUE THREAD

**Issue by zhubin1992** [d3/d3-geo-projection#183]
d3-geo-projection@2.8.0/dist/d3-geo-projection.js (:445)
```
function solve2d(f, MAX_ITERATIONS = 40, eps = epsilon2) {
  return function(x, y, a = 0, b = 0) {
    ...
  };
}
```
Default function parameters are ECMAScript 2015.That will cause some errors.

**Comment by zhubin1992** [comment]
We need use Babel  to use the latest JavaScript features that aren't yet supported by browsers and Node.js.

**Comment by Fil** [comment]
My mistake. I always forget. Thank you!

**Comment by mbostock** [comment]
You can add an eslint rule to remind you if you like.
