### ISSUE TITLE
Pangean projection

### ISSUE THREAD

**Issue by gerwitz** [d3/d3-geo-projection#190]
I know this is ridiculous, but it can’t hurt to ask. I’d love to have a projection that maps coordinates to Pangea. E.g. http://capitan-mas-ideas.blogspot.com/2012/08/pangea-politica.html

Obviously useless for marine coordinates and only a novelty for land.

**Comment by Fil** [comment]
Nice idea! I would do it as a preprocessor to a projection so you'd still be able to project pangea with any  projection.

For an example see the _warp_ function in https://observablehq.com/@fil/fisheye-conformal-map#warp

**Comment by Fil** [comment]
(Closing as this is not directly relevant for d3-geo-projection.)

**Comment by TJung1968** [comment]
Maybe I’m not understanding this correctly… but is this even a matter of the projection?
Wouldn’t it be sufficient to have topojson files describing the Pangea coastlines (and, if needed, present-day’s political borders on Pangea)?

**Comment by gerwitz** [comment]
Certainly the map could be drawn in that matter, but my goal is to map arbitrary data with land coordinates to Pangea.

Pre-warping coordinates is a great workaround.

**Comment by Fil** [comment]
I'm [interested](https://observablehq.com/@fil/plate-tectonics), lmk if you need some help with this.
