### ISSUE TITLE
Could not find a declaration file 

### ISSUE THREAD

**Issue by LukaTchubabria** [d3/d3-geo-projection#217]
**Does this library have no types? How to solve this problem?**

import { geoCylindricalStereographic } from "d3-geo-projectio
]
Could not find a declaration file for module 'd3-geo-projection'.

**Comment by mbostock** [comment]
D3 does not maintain TypeScript declarations but some are maintained by the community as part of the DefinitelyTyped project.

**Comment by bykbtzr** [comment]
As a workaround one can declare the needed exports in an ambient declaration (.d.ts file) as follows:

```ts
declare module "d3-geo-projection" {
	import { GeoProjection } from "d3-geo"
	export function geoPatterson(): GeoProjection
}

```
