### ISSUE TITLE
No types definition package of d3-geo-projection

### ISSUE THREAD

**Issue by nickyonge** [d3/d3-geo-projection#226]
Noticed an error in VS Code for a lack of type definitions specifically for `d3-geo-projections`, see image:

![image](https://github.com/d3/d3-geo-projection/assets/2841909/b400e4e3-978a-4acc-be51-c395ef80d5c4)

It suggests `npm i --save-dev @types/d3-geo-projection`, however that results in a 404:
`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fd3-geo-projection - Not found`

Which is true, the NPM registry specifically for d3-geo-projection type definitions isn't found (link to [package](https://www.npmjs.com/package/d3-geo-projection) works, link to [types](https://www.npmjs.com/package/@types/d3-geo-projection) 404s). However, it DOES exist for others, like d3 ([package](https://www.npmjs.com/package/d3), [types](https://www.npmjs.com/package/@types/d3)) and d3-geo ([package](https://www.npmjs.com/package/d3-geo), [types](https://www.npmjs.com/package/@types/d3-geo)).

I have no idea how to generate that package, I also don't know the priority of something like that. Would love to see the docs rounded out :)

**Comment by Fil** [comment]
The types for D3 and its modules are currently community-maintained at https://github.com/DefinitelyTyped/DefinitelyTyped. It would be great to add types for this module too!
