### ISSUE TITLE
Renner's Hemispheric Projection

### ISSUE THREAD

**Issue by espinielli** [d3/d3-geo-projection#228]
I have found a nice projection in Fig 24, pag 62-63 in

> Renner, George Thomas "[Human Geography in the Air Age -- A Text for High School Students](https://archive.org/details/humangeographyin00rennrich)", 1942, The MacMillan Company, New York.

![renner](https://github.com/d3/d3-geo-projection/assets/891692/58bc4698-ecb1-4584-b43f-f2c91a95bdc6)

It is also present/defined in Fig. 2D of
> George T. Renner "The Globe and the Map", Teachers College Record 47 (7), 1-14
but I have no way to access this source.

Any suggestions where to find details/math for implementing it?

I put what I know in https://observablehq.com/@espinielli/renner-hemispheric-projection

**Comment by Fil** [comment]
The base is ~~most probably a Mollweide~~?
https://observablehq.com/@fil/renners-hemispheric-projection

You can try to replace with ~~geoFaheyRaw~~ for a nicer(?) aspect ratio

(See below for apian II)

**Comment by rschmunk** [comment]
Not a Mollweide variant as the parallels are equally spaced. Looks like a variant of the Apian II aka Arago.

**Comment by rschmunk** [comment]
This is what I get emulating that map using the Apian II (Arago) as a start.

![Renner](https://github.com/d3/d3-geo-projection/assets/8718035/6ef29b2d-7dd0-426f-a6ea-ad7d7a1585d1)

(This is using my own Java code and not using D3.)

**Comment by Fil** [comment]
Good call! I've updated my notebook.

**Comment by espinielli** [comment]
eh, eh, I did it as well ;-)
(I am puzzled at not finding a description of it...)

**Comment by rschmunk** [comment]
For extra confusion...

I noted that the graphic indicated Renner claimed copyright 1928. I started looking around to see if I could find what that publication might be. Didn't find it, but I did discover a monograph published in 1927 with a map that for an instant I thought was the same, then realized the two halves of the Northern Hemisphere were polyconics rather than pseudocylindrics.

<img width="450" alt="1927_Renner-map _copy" src="https://github.com/d3/d3-geo-projection/assets/8718035/b0c977e9-2682-40a6-9af8-64200cebeea8">

This is from "[Primitive religion in the tropical forest](https://catalog.hathitrust.org/Record/001274803)", inserted between pages 24 and 25.

**Comment by espinielli** [comment]
yes @rschmunk I had tried to search for the patent too but no luck there...it's always archeology!

**Comment by rschmunk** [comment]
I found a Library of Congress catalog listing 1928 copyrights, and the map section includes a "World climatic map" on "Renner's Homalographic Projection" published December that year in Seattle. It appears to be just that, a map. No book or article, just a map.

Renner may have then used it in a book published in 1930, although I'm still trying to get more info about that. It would not surprise me if it was also used in other geography book(s) he (co)authored, including one published in 1936.

**Comment by Fil** [comment]
There are lots of maps, including a chapter dedicated to projections in https://archive.org/details/globalgeography00renn/ but I didn't see that particular projection (I might have missed it it's a big book).

**Comment by rschmunk** [comment]
I am reminded that the Apian II has been called the Equidistant Mollweide in at least one source, so @Fil's original guess wasn't entirely off-base.

**Comment by espinielli** [comment]
> There are lots of maps, including a chapter dedicated to projections in https://archive.org/details/globalgeography00renn/ but I didn't see that particular projection (I might have missed it it's a big book).

I went thru the whole book too and didn't find any plot of Renner's Hemispherical projection

**Comment by rschmunk** [comment]
The 1928 map was published by the University of Washington when Renner studied or taught there, but I couldn't find anything in their library catalog for that or for something else supposedly published there in 1930.

There's a book by White and Renner from 1936 that I thought might be a good possibility, but no. Most of the global maps there use the Denoyer projection.

**Comment by espinielli** [comment]
I added (modern) climate zones in [my notebook](https://observablehq.com/@espinielli/renner-hemispheric-projection) (still missing graticule coordinates labels...)
![renner_climate](https://github.com/d3/d3-geo-projection/assets/891692/85161e68-ac1b-4eeb-ba4a-dae8a68c7ea8)
