### ISSUE TITLE
Dymaxion projection?

### ISSUE THREAD

**Issue by poelzi** [d3/d3-geo-projection#25]
The Dymaxion map projection would be utterly awesome :)

**Comment by Fil** [comment]
it's already there, by @jasondavies 

https://www.jasondavies.com/maps/airocean/
https://github.com/d3/d3-plugins/issues/61

**Comment by jrus** [comment]
This uses a Gnomonic projection, not Fuller’s.

**Comment by Fil** [comment]
Are we able to include this for #32? Would make a nice addition

**Comment by mbostock** [comment]
Doubtful. It looks like Jason has taken down the code (which as far as I know was never released under an open-source license).

**Comment by jrus** [comment]
Papers:
http://www.tandfonline.com/doi/pdf/10.1559/152304094782540628
http://www.utpjournals.press/doi/pdf/10.3138/1677-3273-Q862-1885

**Comment by Fil** [comment]
https://www.openstreetmap.org/user/smaprs/diary/39829

Dymaxion C/Python script at: http://emergentweirdness.blogspot.fi/2012/03/dymaxion-conversion.html

**Comment by curran** [comment]
Would be a sweet projection to have available.

@Fil Following links from that emergentwierdness link, I tracked down this [quasi-README for the C code that implements the projection](http://www.rwgrayprojects.com/rbfnotes/maps/graymap6.html) by [Robert W. Gray](http://www.rwgrayprojects.com/).

Some interesting images from there:

![](http://www.rwgrayprojects.com/rbfnotes/maps/images/outline1.gif)

![](http://www.rwgrayprojects.com/rbfnotes/maps/images/outline2.gif)

These seem to be a map of sorts for navigating his [C implementation of the Dymaxion projection](http://www.rwgrayprojects.com/rbfnotes/maps/docs/graypr.c).

Maybe this C implementation could be a useful blueprint. Note the license:

```
/**************************************************************/
/*                                                            */
/* This C program is copyrighted by  Robert W. Gray and may   */
/* not be used in ANY for-profit project without written      */
/* permission.                                                */
/*                                                            */
/**************************************************************/
```

Also related to https://github.com/OSGeo/proj.4/issues/232 **Add Dymaxion/Fuller Projection** which, interestingly, links to this [JavaScript implementation of the Dymaxion projection](https://github.com/mbostock/protovis/blob/gh-pages/ex/dymax.js) by @mbostock . Here's a [working JavaScript Dymaxion choropleth](http://mbostock.github.io/protovis/ex/dymax.html) that uses that implementation with Protovis ([source](https://github.com/mbostock/protovis/blob/gh-pages/ex/dymax.html)).

![image](https://cloud.githubusercontent.com/assets/68416/20649506/adbc01d8-b4e7-11e6-97f0-35a552d63c25.png)

**Comment by mbostock** [comment]
That was contributed by Vadim Ogievetsky, and I believe it was a direct port from the C code you linked, and therefore is missing appropriate attribution. I will add attribution shortly.

**Comment by mbostock** [comment]
Attribution added in mbostock/protovis@b653a8cccd7249c155466c6b75b4268fbb754853.

**Comment by Fil** [comment]
Now fully implemented in [d3-geo-polygon(newprojections branch)](https://github.com/d3/d3-geo-polygon/tree/newprojections), but it needs a new release of d3-geo (https://github.com/d3/d3-geo/pull/128) before it's usable.

**Comment by Fil** [comment]
![airocean](https://user-images.githubusercontent.com/7001/37122637-a0b932ce-2261-11e8-978d-c427be35c974.png)

Now fully implemented in [d3-geo-polygon](https://github.com/d3/d3-geo-polygon).

To avoid any IP issue I made a fresh implementation of the triangle transformation, and avoided the (possibly though not probably) trademarked name "Dymaxion".

https://beta.observablehq.com/@fil/airocean-projection
https://beta.observablehq.com/@fil/buckminster-fullers-triangle-transformation

**Comment by mbostock** [comment]
Looks great, @Fil! My only suggestion is to rotate it 90° so it’s bigger on tall screens (as [Jason did previously](https://www.jasondavies.com/maps/airocean/)).

**Comment by Fil** [comment]
Arguments in favor of keeping this as the standard orientation:

1. it fits 960x500 better

2. same as https://www.bfi.org/about-fuller/big-ideas/dymaxion-world/
dymaxion-map and Jasper Johns's painting.

**Comment by mbostock** [comment]
I didn’t mean to make that the default, I just meant in your demo…
