### ISSUE TITLE
Update to D3 4.0.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo-projection#32]
- [x] d3.geoAitoff
- [x] d3.geoAiry
- [x] d3.geoAlbers
- [x] d3.geoArmadillo
- [x] d3.geoAugust
- [x] d3.geoAzimuthalEqualArea
- [x] d3.geoAzimuthalEquidistant
- [x] d3.geoBaker
- [x] d3.geoBerghaus
- [x] d3.geoBoggs
- [x] d3.geoBonne
- [x] d3.geoBottomley
- [x] d3.geoBromley
- [x] d3.geoChamberlin
- [x] d3.geoCollignon
- [x] d3.geoConicConformal
- [x] d3.geoConicEquidistant
- [x] d3.geoCraig
- [x] d3.geoCraster
- [x] d3.geoCylindricalEqualArea
- [x] d3.geoCylindricalStereographic
- [x] d3.geoEckert1
- [x] d3.geoEckert2
- [x] d3.geoEckert3
- [x] d3.geoEckert4
- [x] d3.geoEckert5
- [x] d3.geoEckert6
- [x] d3.geoEisenlohr
- [x] d3.geoEquirectangular
- [x] d3.geoFahey
- [x] d3.geoFoucaut
- [x] d3.geoGilbert
- [x] d3.geoGingery
- [x] d3.geoGinzburg4
- [x] d3.geoGinzburg5
- [x] d3.geoGinzburg6
- [x] d3.geoGinzburg8
- [x] d3.geoGinzburg9
- [x] d3.geoGnomonic
- [x] d3.geoGringorten
- [x] d3.geoGringortenQuincuncial
- [x] d3.geoGuyou
- [x] d3.geoHammer
- [x] d3.geoHammerRetroazimuthal
- [x] d3.geoHealpix
- [x] d3.geoHill
- [x] d3.geoHomolosine
- [x] d3.geoInterrupted
- [x] d3.geoKavrayskiy7
- [x] d3.geoLagrange
- [x] d3.geoLarrivee
- [x] d3.geoLaskowski
- [x] d3.geoLittrow
- [x] d3.geoLoximuthal
- [x] d3.geoMercator
- [x] d3.geoMiller
- [x] d3.geoModifiedStereographic
- [x] d3.geoModifiedStereographicAlaska
- [x] d3.geoModifiedStereographicGs48
- [x] d3.geoModifiedStereographicGs50
- [x] d3.geoModifiedStereographicMiller
- [x] d3.geoModifiedStereographicLee
- [x] d3.geoMollweide
- [x] d3.geoMtFlatPolarParabolic
- [x] d3.geoMtFlatPolarQuartic
- [x] d3.geoMtFlatPolarSinusoidal
- [x] d3.geoNaturalEarth
- [x] d3.geoNellHammer
- [x] d3.geoOrthographic
- [x] d3.geoPatterson
- [x] d3.geoPeirceQuincuncial
- [x] d3.geoPolyconic
- [x] d3.geoRectangularPolyconic
- [x] d3.geoRobinson
- [x] d3.geoSatellite
- [x] d3.geoSinusoidal
- [x] d3.geoSinuMollweide
- [x] d3.geoStereographic
- [x] d3.geoTimes
- [x] d3.geoTransverseMercator
- [x] d3.geoTwoPointAzimuthal
- [x] d3.geoTwoPointEquidistant
- [x] d3.geoVanDerGrinten
- [x] d3.geoVanDerGrinten2
- [x] d3.geoVanDerGrinten3
- [x] d3.geoVanDerGrinten4
- [x] d3.geoWagner4
- [x] d3.geoWagner6
- [x] d3.geoWagner7
- [x] d3.geoWiechel
- [x] d3.geoWinkel3

**Comment by Fil** [comment]
- [x] d3.geoBottomley done locally

Before I continue I have an issue with the image resolution for the tests: the test output is visually OK but not the same as those in img/

For reference I'm attaching the result of `npm test` for mollweide: it's 209KB instead of 82.6KB for [img/mollweide.png](https://github.com/d3/d3-geo-projection/blob/4/img/mollweide.png)

![mollweide](https://cloud.githubusercontent.com/assets/7001/16486340/64b8b36c-3ec4-11e6-8dea-d6206aaa0f92.png)

**Comment by Fil** [comment]
instructions from @mbostock to play this game:
> Take a look at the past commits to get a sense of what’s needed.
> e.g., https://github.com/d3/d3-geo-projection/commit/2ed796f64e2628bfff0c8bc70d2898936dfb4876
> 1. Replace the Greek with anglicized ASCII.
> 2. Replace the `Math.` prefix with an import.
> 3. Fix the imports.
> 4. Update the tests.
> 5 Add reference image to the README.

**Comment by Fil** [comment]
my recipe for setting up the dev environment, in case it can help others: https://gist.github.com/Fil/5f8c92efadd183670ae8c63a060f03b8

**Comment by mbostock** [comment]
The difference in size is expected. I run the output images through [optipng](http://optipng.sourceforge.net/) (`brew install optipng` on macOS) before adding them to the img folder so they are smaller to download. The test uses imagemagick to compare just the pixel values, not the non-image information.

**Comment by mbostock** [comment]
Also re. your Gist, you can simplify slightly and just `npm install` because all those things are listed as dependencies (or devDependencies) in the package.json.

**Comment by Fil** [comment]
I've just pushed a PR claiming winkel3. Incomplete but up for comments.

tests were failing on my Mac due to an old version of `compare` that was on the path (`/Applications/MAMP/Library/bin` : ImageMagick 6.8.9-7); I've replaced it by ImageMagick 6.9.4-9 Q16 and it works.

Re: npm install, I thought I did just that, but maybe I didn't.

One question: how do you choose and specify the default scale? Just so that it fits well in the 960/500 reference canvas?

**Comment by mbostock** [comment]
> Just so that it fits well in the 960/500 reference canvas?

Yes; typically with a 10px margin. Also pick suitable clipping, since not every projection wants antimeridian clipping.

**Comment by mbostock** [comment]
I’ve started trying to do a mass translation over here:

https://github.com/d3/d3-geo-projection/tree/4-broken

**Comment by Fil** [comment]
The game looks simpler now 🤖. Please give the new rules.

**Comment by mbostock** [comment]
The rules are the same. It’s just that I have now applied an indeterminate
number of them via regex to the 4-broken branch, so it is up to the player
to figure out what is left to do!

I’d probably still recommend pulling them out of the 4-broken branch one by
one and merging them into 4 when they work. (You can use 'git cat-file blob
4-broken:src/foo.js' to extract individual files into the current branch.)

**Comment by Fil** [comment]
Another question: wouldn't it be neater to `.rotate([-11.5,0])` by default on most projections so that we cut in the waters?
![robinson](https://cloud.githubusercontent.com/assets/7001/16539939/c7bf8bc2-4052-11e6-8835-c246021c2b3b.png)

**Comment by mbostock** [comment]
Hmm. I can see the appeal in that, but I also think it’s best to stick with the exact standard aspect by default. Better to just suggest that as a better default aspect in the README, say in the top introduction (which needs pictures anyway!).

**Comment by Fil** [comment]
OK. I'd keep it in a funky projection such as Wiechel (where you had put it in v3)
https://github.com/d3/d3-geo-projection/pull/38/files#diff-7aedb1c4d81a3fbd4bf980fc6e6bd479
![](https://raw.githubusercontent.com/d3/d3-geo-projection/6ecff6f5fe2bb9c8764d3add5de15425f8d7a023/img/wiechel.png)

**Comment by mbostock** [comment]
Yep!

**Comment by Fil** [comment]
The visual tests are probably sufficient to test projections, but what about inverse projections? Can we use a systematic method? Maybe test a given or random set of points?

**Comment by mbostock** [comment]
A standard set of test points would be nice for testing inverse
projections, say, some major cities plus maybe some odd things like McMurdo
in Antarctica. (Though I’d refrain from testing exact edge cases like the
poles and the antimeridian since those are often discontinuities.)

I’d also want to test projection.rotate and projection.center for all the
projections and inverse projections, or at least for the ones with custom
streams like Gilbert.

**Comment by mbostock** [comment]
I’ve decided that rather than try to apply some variable padding to each projection, to just fit them exactly into 960×500 using the new test/compute-scale.

**Comment by Fil** [comment]
HowIHateCamelCase

**Comment by Fil** [comment]
I'm leaving the game now, not seing straight and I think these are too difficult:
- d3.geoHealpix
- d3.geoHomolosine
- d3.geoInterrupted
- d3.geoTwoPointAzimuthal
- d3.geoTwoPointEquidistant

**Comment by mbostock** [comment]
Thanks for all your work! 👍 

I merged as many as I could, but I’m on vacation now and want to spend some time with family. I’ll take another pass sometime later…

**Comment by mbostock** [comment]
I merged to master. Still have to implement the two-point and interrupted projections, but that should happen soon. And then 1.0!

**Comment by mbostock** [comment]
🎉
