### ISSUE TITLE
Built-in interrupted projections.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo-projection#36]
- [x] [Boggs Eumorphic](http://bl.ocks.org/mbostock/4481265)
- [x] [Goode Homolosine](http://bl.ocks.org/mbostock/4448587)
- [x] [Mollweide](http://bl.ocks.org/mbostock/4498187)
- [x] [Mollweide Hemispheres](http://bl.ocks.org/mbostock/4498292)
- [x] [Sinusoidal](http://bl.ocks.org/mbostock/4458991)
- [x] [Sinu-Mollweide](http://bl.ocks.org/mbostock/4481520)

Seems a bit strange that we don’t provide some of the standard interrupted projections as built-ins. For example, the [interrupted Goode homolosine](http://bl.ocks.org/mbostock/4448587) projection could be defined as:

```js
import {homolosineRaw} from "./homolosine";
import interrupt from "./interrupt";

export default interrupt(homolosineRaw)
    .lobes([[ // northern hemisphere
      [[-180,   0], [-100,  90], [ -40,   0]],
      [[ -40,   0], [  30,  90], [ 180,   0]]
    ], [ // southern hemisphere
      [[-180,   0], [-160, -90], [-100,   0]],
      [[-100,   0], [ -60, -90], [ -20,   0]],
      [[ -20,   0], [  20, -90], [  80,   0]],
      [[  80,   0], [ 140, -90], [ 180,   0]]
    ]]);
```

**Comment by jrus** [comment]
Will `interrupt` ever go into `d3-geo`, or is it only relevant in `d3-geo-projection`?

**Comment by mbostock** [comment]
My inclination was to put it in d3-geo-projection but it is very small and
generally useful, so I wouldn’t mind moving it to d3-geo. Especially if
there are any common interrupted projections that use the common
projections already in d3-geo?

**Comment by mbostock** [comment]
Added!
