### ISSUE TITLE
Cahill–Keyes projection?

### ISSUE THREAD

**Issue by maphew** [d3/d3-geo-projection#6]
I've dreamt for years now of porting the [Cahill-Keyes butterfly projection](http://www.wired.com/wiredscience/2013/11/cahill-butterfly-vs-dymaxion-map/) to a GIS platform. The existing CK formulas are brute force, I'm sure there's a lot of room to simplify and convert to actual algorithms, but my math skills are too weak for the task (and my time management weaker!). 

So I'm lobbing the ball over here in the hopes someone else will be sufficiently inspired to carry it out.

**Comment by Fil** [comment]
I would like to help with this. What is the current status, what needs to be done?

**Comment by espinielli** [comment]
The implementation of the perl code from Gene Keyes site is available in my implementation.
All is needed is to make it fit Jason Davies plugin...but I never really got the time to fully understand it.

**Comment by mbostock** [comment]
@espinielli If your code is open-sourced under a LICENSE and you can point me to it, I’d be happy to do the work to setup a d3-geo-cahill-keyes repository and host it there. Assuming it doesn’t need Jason’s clip-to-spherical-polygon feature which hasn’t been released yet (sounds like it doesn’t https://github.com/d3/d3-plugins/pull/69#issuecomment-19895660).

**Comment by espinielli** [comment]
Running code is in these blocks

http://bl.ocks.org/espinielli/5689783
http://bl.ocks.org/espinielli/b6e2f37814a19dc461f8
http://bl.ocks.org/espinielli/e1e4f9429aa386de6214

The last one is a rotating version and it shows that probably clip-to-spherical is in need...

License is DWYWAMCM: do whatever you want and maybe cite me ;-)

Some years ago I submitted a PR to have it included but had never really time to study/understand and make my implementation fully in line with Jason d3.polyhedral projections...even if I started from that same code...

**Comment by Fil** [comment]
🦄
https://beta.observablehq.com/@fil/cahill-keyes-projection
https://github.com/d3/d3-geo-polygon/pull/8

**Comment by espinielli** [comment]
You should send an email to Gene...he would be delighted

**Comment by Fil** [comment]
Good idea, will do.

**Comment by maphew** [comment]
claps and cheers! Thank you :+1:
