### ISSUE TITLE
Group README by projection properties.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo-projection#65]
Inspired partly by https://en.wikipedia.org/wiki/List_of_map_projections, some possible categories:
- conformal
- equal-area
- equidistant
- retroazimuthal
- compromise
- other
- interrupted (and polyhedral?)

**Comment by jrus** [comment]
I believe this is one of the better known discussions of projection classification:
http://www.csiss.org/map-projections/Reference/Maling_1968.pdf

**Comment by mbostock** [comment]
Too hard!
