### ISSUE TITLE
Fix all invert projections

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-projection#70]
Except those that can't be fixed, maybe.

The list of broken invert projections is given by the lines that are commented out in https://github.com/Fil/d3-geo-projection/blob/invert-tests/test/invert-test.js

**Comment by Fil** [comment]
this issue should probably be left open since a dozen or so inverse projections do not pass (the tests have been disabled, but still…)
The question being, which ones can't be fixed at all, which ones might be mathematically inversed (with some work), and which ones would be relatively okay if we used an approximate algorithm to invert them (https://github.com/Fil/pmp-sample-maps/blob/master/lib/newton.v1.js).

**Comment by mbostock** [comment]
It might be better to open an issue for each broken inverse projection.
