### ISSUE TITLE
geoproject --require

### ISSUE THREAD

**Issue by mbostock** [d3/d3-geo-projection#83]
We should support --require so that you can load third-party plugins such as [d3-stateplane](https://github.com/veltman/d3-stateplane) / [d3-geo-state-plane](https://github.com/gka/d3-geo-state-plane).

**Comment by mbostock** [comment]
Related mbostock/ndjson-cli#8.

**Comment by Fil** [comment]
@rveciana I just saw you solved this already in https://github.com/rveciana/d3-geo-projection/commit/b581ab0dad758825144160ab9fce7ef6301a0717; please send a pull-request next time :)

**Comment by rveciana** [comment]
It was a test! I don't know if it's correct enough for integration.

El dt., 21 ag. 2018, 13.33, Philippe Rivière <notifications@github.com> va
escriure:
