### ISSUE TITLE
Algorithmic search for inverse projections

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-projection#85]
It would be nice to be able to fall back on an algorithmic search (Newton-Raphson) when inverse isn't defined, for any projection.

Several inverse projections already do this, but it's not centralized (example: https://github.com/d3/d3-geo-projection/search?q=Newton-Raphson).

Related:
https://github.com/d3/d3-geo-projection/issues/70
https://github.com/d3/d3-geo/issues/69#issuecomment-262854500

**Comment by Fil** [comment]
https://marcinciura.wordpress.com/2016/11/20/authagraph/ has this note:

> As inverting the equations of the projection algebraically is a hopeless task, I resorted to the numerical Broyden’s method. The initial guess of (\phi, \lambda) = f^{-1}(x, y) comes from inverting the gnomonic projection. When the accuracy is set to 10-7 R, i.e. about one metre, the method usually finds \phi and \lambda after 5 iterations.

**Comment by Fil** [comment]
@mciura I cited you here also

**Comment by mciura** [comment]
In my experience, Broyden's method had the median number of iterations equal to 5, and the long tail ended at 18 or 19 iterations. I had to come up with nontrivial tricks to make it work near the poles — I suppose Newton–Raphson and any other method would need them too.

**Comment by Fil** [comment]
Here's a function that apparently works correctly for the inverse of:
- ChamberlinAfrica
- ModifiedStereographicAlaska
- ModifiedStereographicGs48
- ModifiedStereographicMiller
- ModifiedStereographicLee
- TwoPointAzimuthalUsa

It's not perfect with:
- GringortenQuincuncial (Northern hemisphere OK, Southern broken)
- ModifiedStereographicGs50 (the part over Europe is broken)

It doesn't work at all with
- InterruptedSinuMollweide (though it's probably simple to fix in interrupted.js)

 https://bl.ocks.org/Fil/07930ee04d7fbd9e5e3e84e803d35dcf 

![chamberlinafrica invert](https://cloud.githubusercontent.com/assets/7001/24365298/ca39cffc-1315-11e7-880b-0b78f2062534.png)

**Comment by Fil** [comment]
This inverse function now works on _all_ remaining d3 projections.

The code would need to be cleaned up before merging, and before I try and do that, I'd like to know if you think the 2D (and spherical) Newton-Raphson method should be promoted into its own plugin (d3.solve, d3.geoSolve), rather than be constrained to d3-geo.
