### ISSUE TITLE
Icosahedral map

### ISSUE THREAD

**Issue by linard-y** [d3/d3-geo-projection#87]
I would like to create a gnomonic icosahedral map (not a Fuller map, just a simple icosaheral map based on a simple icosahedral net) but as a neophyte in this area, i take inspiration from the gnomonic buterfly (octahedron) and my difficulty is to understand these lines in the buterfly.js code:
```
[-1, 0, 0, 1, 0, 1, 4, 5].forEach(function(d, i) {
    var node = faces[d];
    node && (node.children || (node.children = [])).push(faces[i]);
 });
```
What is the array [-1, 0, 0, 1, 0, 1, 4, 5] ? Could you give some reference to understand that ?
Thanks.

**Comment by Fil** [comment]
`faces` is a list of the 8 faces, numbered 0 to 7.

`[-1, 0, 0, 1, 0, 1, 4, 5]` shows which face is the parent of faces 0…7, i.e. face 0 has no parent, faces 1 and 2 are children of face 0, faces 3 and 5 are children of face 1, etc.

( I'm not sure this  ad-hoc code can be generalized to other topologies, such as for myriahedral https://github.com/d3/d3-geo-projection/issues/67 )

**Comment by linard-y** [comment]
Hi Philippe,

Thanks a lot for this explaination.

Yannick

**Comment by Fil** [comment]
@espinielli has one running here https://bl.ocks.org/espinielli/475f5fde42a5513ab7eba3f53033ea9e
Note that it still needs a little bit of work on d3-geo's clipPolygon to be really usable ([#46](https://github.com/d3/d3-geo/issues/46)).

**Comment by Fil** [comment]
Now fully implemented in [d3-geo-polygon(newprojections branch)](https://github.com/d3/d3-geo-polygon/tree/newprojections), but it needs a new release of d3-geo (https://github.com/d3/d3-geo/pull/128) before it's usable.
