### ISSUE TITLE
Antimeridian Cutting for interrupted projections

### ISSUE THREAD

**Issue by yalongyang** [d3/d3-geo-projection#95]
The antimeridian cutting is such a great feature!
However, it seems it cannot work for interrupted projections.

I modified the code of [Antimeridian Cutting example](https://bl.ocks.org/mbostock/3788999) to change to projection to "geoInterruptedHomolosine" and it cannot cut properly.

**Comment by mbostock** [comment]
Works fine for me?

https://bl.ocks.org/mbostock/aaa69d969b714ecb05bac01e2a29dd41

Perhaps you missed this note from the [README](https://github.com/d3/d3-geo-projection/blob/master/README.md#interrupted-projections)?

> Note: interrupted projections typically require clipping to the sphere.

**Comment by yalongyang** [comment]
I understand it now. The antimeridian cutting is used to present the "mis-connections" between left and right also top and bottom. The "mis-connections" between gores are dealt with svg path clip.

Thanks for your reply!

Actually, d3 is so good for maps. However, it cannot be used in unity3d. I want to create some immersive maps, and there is no library has the antimeridian cutting feature in c#. So the only choice for me is to set up a d3 server, and use RPC to get the map data. Everything goes well at the moment, I still need to create a unity3d version of svg path clip of course, and the RPC takes 2s each call...

Anyway, thank you so much.
