### ISSUE TITLE
Error started appearing after recent release to 4.7.1

### ISSUE THREAD

**Issue by jodibean** [d3/d3-geo-projection#96]
Greetings!

We have some geoJSON files that are giving us unexpected errors after the recent release of 4.7.1. Not all of them are failing, which is strange.  All of the ones that are failing validate in a geoJSON validator just fine. No changes have been made to these files in the last 4 months.

The error we receive is "Error: <path> attribute d: Expected number, "MNaN,NaNLNaN,NaN"
Our code is below. And the JSON is attached. 
[0157_02_json.txt](https://github.com/d3/d3-geo-projection/files/822122/0157_02_json.txt)

Any idea why this is happening?
`
               vm.projection = d3.geoMercator().rotate([0, vm.rotation]);
                vm.path = d3.geoPath()
                    .projection(vm.projection.fitExtent([[0, 0], [vm.w, vm.h]], json));

                vm.svg.selectAll(".room")
                    .data(vm.rooms)
                    .enter().append("path")
                    .attr("class", "room")
                    .attr("d", vm.path)
                    .attr("fill", "#fff")
                    .attr("stroke", "none")
                    .attr("id", function (d) {
                        return d.properties.loc;
                    })
                    .on("mouseover", function (d) {
                        vm.div.transition()
                            .duration(90)
                            .style("opacity", 1);
                        vm.div.html(d.properties.room)
                            .style("left", (d3.event.pageX) + "px")
                            .style("top", (d3.event.pageY - 28) + "px");
                    })
                    .on("mouseout", function (d) {
                        vm.div.transition()
                            .duration(90)
                            .style("opacity", 0);
                    })
                    .on('click', function (d) {
                        d3.selectAll(".room").attr("fill", "#fff").attr("stroke", "none");
                        d3.select(this).attr("fill", "#BBDEFB").attr("stroke-width", "2").attr("stroke", "#FF5722");
                        vm.handleClick(d);
                    });`

**Comment by mbostock** [comment]
I wasn’t initially able to reproduce this…

[![untitled 10](https://cloud.githubusercontent.com/assets/230541/23624481/b0a28b54-025a-11e7-9bb4-94485271951a.png)](https://bl.ocks.org/mbostock/016839acd1bafdf9c119a264c1b71723/ec7cb9d088938b80dbc4d332d374976f616eeb72)

However, I discovered if you set the rotation to be greater than 85° (which probably not coincidentally is the latitudinal limit of the default clip extent), then it breaks. This is probably related to the Mercator fixes in [d3-geo@1.6.1](https://github.com/d3/d3-geo/releases/tag/v1.6.1), so I am moving the issue there.

**Comment by mbostock** [comment]
Moved to d3/d3-geo#89.
